title: Leagueopoly
email: michael@therandommelon.com
description: The official website of Leagueopoly, an esports league based on the online Monopoly clone Richup.io.
baseurl: ""
url: https://leagueopoly.com
urlnp: leagueopoly.com
twitter: https://twitter.com/Leagueopoly
github: https://github.com/MeloniaGov/main-site
permalink: /news/:year/:title
desc: The official website of Leagueopoly, an esports league based on the online Monopoly clone Richup.io.

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  players:
    output: true
    sort_by: player_name
    # it would be nice to use player_id here, but jekyll doesn't support that
    # "name" is just the filename, so trm.md -> /players/trm
    permalink: /players/:name

defaults:
  - scope:
      path: ""
      type: "players"
    values:
      layout: "players"
      # not sure what keywords is used for but it was in every player, so added here -tom
      keywords: "players"